import { useEffect, useState } from "react";

type MeanCI = Record<string, number | null>;
type Results = {
  monte_carlo_means: Record<string, Record<string, number | null>>;
  monte_carlo_ci: Record<string, Record<string, number | null>>;
  mission_effectiveness: {
    scores: Record<string, {
      mes: number; mission_capable: boolean;
      kpps: Record<string, { pass: boolean; value: number }>;
    }>;
    ranking: string[];
    kpps: Record<string, { min?: number; max?: number; why?: string }>;
  } | null;
  identification: { accuracy?: number };
};

const TITLES: Record<string, string> = {
  "smart-scan": "SmartScan (proposed)",
  "bandit-ucb": "UCB bandit",
  "rl-linear-q": "Q-learning (linear)",
  "rl-dqn": "Deep Q-network",
  "openloop-random": "Random scan",
  "openloop-priority": "Priority sweep",
  "openloop-sequential": "Sequential sweep",
};

export function useResults(): Results | null {
  const [r, setR] = useState<Results | null>(null);
  useEffect(() => {
    fetch("/data/results.json").then((x) => x.json()).then(setR).catch(() => undefined);
  }, []);
  return r;
}

export function Logo({ size = 28 }: { size?: number }) {
  return <img src="/astra_logo.svg" alt="ASTRA logo" width={size} height={size} />;
}

export function Nav() {
  return (
    <nav className="nav">
      <div className="nav-inner">
        <a className="brand" href="/"><Logo /><span className="brand-name">ASTRA</span></a>
        <div className="nav-links">
          <a href="#problem">Problem</a>
          <a href="#how">How it works</a>
          <a href="#results">Results</a>
          <a href="/console.html">Console</a>
          <a href="/documentation.html">Docs</a>
          <a className="nav-download" href="/ASTRA-Setup-1.0.0.exe" download>Download</a>
        </div>
      </div>
    </nav>
  );
}

export function Footer() {
  return (
    <div className="footer-grid">
      <div className="footer-brand">
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}>
          <Logo size={26} />
          <span className="brand-name" style={{ fontSize: 15, letterSpacing: 4 }}>ASTRA</span>
        </div>
        <p>Adaptive Spectrum Threat Recognition &amp; Analysis.</p>
        <p>A prototype developed for Smart India Hackathon 2026. Simulation-based research software, not operational equipment.</p>
      </div>
      <div className="footer-col">
        <h4>Product</h4>
        <a href="/console.html">Console</a>
        <a href="/documentation.html">Documentation</a>
        <a href="/ASTRA-Setup-1.0.0.exe" download>Download</a>
        <a href="#results">Results</a>
      </div>
      <div className="footer-col">
        <h4>Research</h4>
        <a href="#how">Methodology</a>
        <a href="#capabilities">Capabilities</a>
        <a href="#">Experiment Suite</a>
      </div>
      <div className="footer-col">
        <h4>Team</h4>
        <a href="#">About Us</a>
        <a href="#">SIH 2026</a>
        <a href="#">Contact</a>
      </div>
      <div className="footer-bottom" style={{ gridColumn: "1 / -1" }}>
        <p>&copy; 2026 ASTRA Project Team. All benchmark figures are generated by the bundled experiment suite from stored seeds and are fully reproducible.</p>
      </div>
    </div>
  );
}

export function GateAndMc() {
  const r = useResults();
  if (!r?.mission_effectiveness) return null;
  const me = r.mission_effectiveness;
  const kppDefs = me.kpps ?? {};

  return (
    <>
      {/* KPP thresholds legend */}
      <div className="kpp-legend">
        <span className="kpp-legend-title">KPP Gate Criteria (all must pass):</span>
        {Object.entries(kppDefs).map(([k, spec]) => {
          const label = k === "threat_intercept_ratio" ? "Threat coverage"
            : k === "pct_correct_predictions" ? "Prediction accuracy"
            : k === "false_alarm_rate" ? "False alarm rate" : k;
          const threshold = "min" in spec
            ? `≥ ${(spec.min! * 100).toFixed(0)}%`
            : `≤ ${(spec.max! * 100).toFixed(2)}%`;
          return <span key={k} className="kpp-tag">{label} {threshold}</span>;
        })}
      </div>

      <div className="table-wrap">
        <table className="results">
          <thead>
            <tr>
              <th>Scheduler</th>
              <th>Verdict</th>
              <th>MES</th>
              <th>Threat coverage</th>
              <th>Prediction accuracy</th>
            </tr>
          </thead>
          <tbody>
            {me.ranking.map((n) => {
              const sc = me.scores[n];
              const cov = sc.kpps["threat_intercept_ratio"]?.value ?? 0;
              const pred = sc.kpps["pct_correct_predictions"]?.value ?? 0;
              const covPass = sc.kpps["threat_intercept_ratio"]?.pass ?? false;
              const predPass = sc.kpps["pct_correct_predictions"]?.pass ?? false;
              return (
                <tr key={n} className={n === "smart-scan" ? "hl" : ""}>
                  <td>{TITLES[n] ?? n}</td>
                  <td>
                    <span className={"pill " + (sc.mission_capable ? "pass" : "fail")}>
                      {sc.mission_capable ? "CAPABLE" : "DISQUALIFIED"}
                    </span>
                  </td>
                  <td className="mono">{sc.mes.toFixed(3)}</td>
                  <td className={"mono " + (covPass ? "kpp-pass" : "kpp-fail")}>
                    {(cov * 100).toFixed(1)}%
                  </td>
                  <td className={"mono " + (predPass ? "kpp-pass" : "kpp-fail")}>
                    {(pred * 100).toFixed(1)}%
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <p className="kpp-note">
        SmartScan is the only scheduler that passes <b>every</b> KPP simultaneously —
        high threat coverage <b>and</b> accurate predictions. Others may score higher
        on individual metrics but fail the all-or-nothing gate.
      </p>
    </>
  );
}
