"""Bake engine outputs into the presentation website as static content.

Produces (all inside website/):
  public/data/results.json      trimmed benchmark payload
  public/figures/*.png          selected evidence figures
  public/docs/manual.md         raw downloadable manual
  src/content/docsHtml.ts       manual pre-rendered to HTML (imported by the docs page)

The website never talks to Python at runtime - everything is baked here so the
site deploys as pure static files (e.g. Vercel).
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "website"

FIGS = ["mission_effectiveness.png", "comparison.png",
        "learning_curves.png", "ablation.png", "roc.png", "geo_cep.png"]


def bake_results() -> dict:
    raw = json.loads((ROOT / "results" / "suite_results.json").read_text("utf-8"))
    out = {
        "monte_carlo_means": {},
        "monte_carlo_ci": {},
        "mission_effectiveness": raw.get("mission_effectiveness"),
        "significance_gated_mes": [
            {k: r[k] for k in ("comparator", "mean_diff", "p_value", "significant")}
            for r in raw.get("significance_gated_mes", [])
        ],
        "identification": raw.get("identification", {}),
        "geolocation": raw.get("geolocation", {}).get("by_receivers", {}),
        "multireceiver": raw.get("multireceiver", {}),
    }
    for name, metrics in raw.get("monte_carlo", {}).items():
        out["monte_carlo_means"][name] = {
            k: v.get("mean") for k, v in metrics.items()}
        out["monte_carlo_ci"][name] = {
            k: v.get("ci95") for k, v in metrics.items()}
    return out


def main() -> None:
    pub = SITE / "public"
    (pub / "data").mkdir(parents=True, exist_ok=True)
    (pub / "figures").mkdir(parents=True, exist_ok=True)
    (pub / "docs").mkdir(parents=True, exist_ok=True)
    (SITE / "src" / "content").mkdir(parents=True, exist_ok=True)

    results = bake_results()
    (pub / "data" / "results.json").write_text(
        json.dumps(results, indent=1), encoding="utf-8")

    for f in FIGS:
        src = ROOT / "figures" / f
        if src.exists():
            shutil.copy2(src, pub / "figures" / f)

    shutil.copy2(ROOT / "docs" / "ASTRA_Software_Documentation.md",
                 pub / "docs" / "manual.md")

    try:
        import markdown as md_lib
        html = md_lib.markdown(
            (ROOT / "docs" / "ASTRA_Software_Documentation.md").read_text("utf-8"),
            extensions=["tables", "fenced_code"])
    except ImportError:
        html = "<pre>markdown package missing - rebuild with: pip install markdown</pre>"

    js_body = json.dumps(html)[:0]  # placeholder to keep linters calm
    safe = json.dumps(html)
    (SITE / "src" / "content" / "docsHtml.ts").write_text(
        "// AUTO-GENERATED by tools/export_site_data.py - do not edit\n"
        f"export const DOCS_HTML = {safe};\n", encoding="utf-8")

    print("website content baked:",
          f"{len(FIGS)} figures, results.json "
          f"({(pub / 'data' / 'results.json').stat().st_size // 1024} KB), "
          f"manual html ({len(html) // 1024} KB)")


if __name__ == "__main__":
    main()
