"""Export the fixed-point decision kernel as compilable C++ (port artifact).

The evaluation criterion "the algorithms are portable to FPGA/DSP" is backed
by a generated artifact rather than a slide: this tool emits
``build/rtl/astra_policy_kernel.hpp`` - a header-only C++ implementation of
:mod:`ewsmart.realtime.PolicyKernel`'s Q8.8 integer arithmetic, with the same
saturation, lazy transcendental caches and O(n_bands) argmax - plus a
``kernel_metadata.json`` complexity contract.

The exported kernel is reference C++ for an RTL/DSP port: it is deterministic,
allocation-free in the hot path, and depends on nothing beyond <cmath>.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from ewsmart.realtime import PolicyKernel

_HEADER = r"""// ASTRA fixed-point scan-policy kernel (auto-generated by
// tools/export_cpp_kernel.py from ewsmart/realtime.py -- do not edit).
// Q8.8 saturating fixed point, O(n_bands) integer MACs per decision,
// no dynamic allocation, no per-slot transcendentals.
#pragma once
#include <cmath>
#include <cstdint>
#include <cstring>

namespace astra {

static constexpr int32_t Q_SHIFT = 8;
static constexpr int32_t Q_ONE = 1 << Q_SHIFT;

inline int32_t sat(int64_t v) {
    constexpr int64_t hi = (int64_t(1) << 31) - 1;
    constexpr int64_t lo = -hi;
    return static_cast<int32_t>(v < lo ? lo : (v > hi ? hi : v));
}

inline int32_t to_q(double x) { return sat(static_cast<int64_t>(x * Q_ONE + (x >= 0 ? 0.5 : -0.5))); }
inline double from_q(int32_t q) { return static_cast<double>(q) / Q_ONE; }

class PolicyKernel {
 public:
  explicit PolicyKernel(int n_bands, double hop_weight = 0.45)
      : n_bands_(n_bands), hop_weight_q_(to_q(hop_weight)),
        mu_q_(new int32_t[n_bands]()), n_q_(new int32_t[n_bands]),
        last_visit_q_(new int32_t[n_bands]()),
        unseen_q_(new int32_t[n_bands]()), lprob_q_(new int32_t[n_bands]()),
        hop_q_(new int32_t[n_bands]()), ucb_q_(new int32_t[n_bands]()),
        recency_q_(new int32_t[n_bands]()) {
    for (int i = 0; i < n_bands; ++i) { n_q_[i] = Q_ONE; }
  }
  ~PolicyKernel() {
    delete[] mu_q_; delete[] n_q_; delete[] last_visit_q_;
    delete[] unseen_q_; delete[] lprob_q_; delete[] hop_q_;
    delete[] ucb_q_; delete[] recency_q_;
  }

  void set_value(int b, double mu) { mu_q_[b] = to_q(mu); }
  void set_visits(int b, double n) { n_q_[b] = to_q(n < 1e-9 ? 1e-9 : n); }
  void set_last_visit(int b, int32_t t) { last_visit_q_[b] = t * Q_ONE; }
  void set_unseen(int b, bool u) { unseen_q_[b] = u ? Q_ONE : 0; }
  void set_logit_prob(int b, double p) { lprob_q_[b] = to_q(p < 0 ? 0 : (p > 1 ? 1 : p)); }
  void set_hop_bonus(int b, double v) { hop_q_[b] = to_q(v < 0 ? 0 : v); }
  void set_time(int32_t t) { if (t != t_) { t_ = t; dirty_ = true; } }

  int step() {
    if (dirty_) refresh();
    int best = 0;
    int64_t best_score = INT64_MIN;
    for (int b = 0; b < n_bands_; ++b) {
      int64_t score = static_cast<int64_t>(mu_q_[b])
          + (55LL * ucb_q_[b]) / 100LL
          + recency_q_[b]
          + (35LL * lprob_q_[b]) / 100LL
          + (static_cast<int64_t>(hop_weight_q_) * hop_q_[b]) / Q_ONE;
      if (best_score == INT64_MIN || score > best_score) {
        best = b; best_score = score;
      }
    }
    ++calls_;
    return best;
  }

 private:
  void refresh() {
    const double lt = std::log(static_cast<double>(t_ < 0 ? 0 : t_) + 2.0);
    for (int b = 0; b < n_bands_; ++b) {
      const double n = from_q(n_q_[b]);
      const double rec = std::sqrt(std::max(0.0, static_cast<double>(
          t_ - static_cast<int32_t>(from_q(last_visit_q_[b])))));
      const double unseen = from_q(unseen_q_[b]);
      ucb_q_[b] = to_q(std::sqrt(lt / n));
      recency_q_[b] = to_q((0.16 + 0.14 * unseen) * rec);
    }
    dirty_ = false;
  }

  int n_bands_;
  int32_t hop_weight_q_;
  int32_t t_ = -1;
  bool dirty_ = true;
  int64_t calls_ = 0;
  int32_t *mu_q_, *n_q_, *last_visit_q_, *unseen_q_;
  int32_t *lprob_q_, *hop_q_, *ucb_q_, *recency_q_;
};

}  // namespace astra
"""


@dataclass
class ExportResult:
    header_path: Path
    metadata_path: Path
    header_lines: int


def export_kernel(out_dir: str | Path = "build/rtl",
                  n_bands: int = 24) -> ExportResult:
    """Emit the C++ kernel header and the complexity-contract JSON."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    header = out / "astra_policy_kernel.hpp"
    header.write_text(_HEADER, encoding="utf-8")
    kernel = PolicyKernel(n_bands)
    meta = kernel.metadata()
    meta["source_module"] = "ewsmart.realtime.PolicyKernel"
    meta["generator"] = "tools/export_cpp_kernel.py"
    meta["n_bands"] = n_bands
    meta_path = out / "kernel_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return ExportResult(header, meta_path, len(_HEADER.splitlines()))
